### ISSUE TITLE
Returning 404 while attempting to reload contact page via the browser.

### ISSUE THREAD

**Issue by ishamsu** [MakerGram/makergram.com-support#1]
Found an issue of urls returning 404 while attempting to reload it via the browser.

**Steps to reproduce**

1. Go to [MakerGram.com](https://makergram.com/)
2. Scroll down to Footer and Click Contact 
3. Refresh the page.

**Expected behaviour**

Contact page should be shown when refreshing or opening the page from another tab

**Screenshot**

![Screenshot 2021-09-27 at 8 21 00 PM](https://user-images.githubusercontent.com/59248733/134938322-3db65d8a-cc21-4b65-ab39-632c0416ef5c.png)

![Screenshot 2021-09-27 at 8 56 36 PM](https://user-images.githubusercontent.com/59248733/134938457-72ad02cd-45ea-4ab6-9e3a-387e50365a60.png)

![Screenshot 2021-09-27 at 8 20 35 PM](https://user-images.githubusercontent.com/59248733/134938500-7f0fdc86-1b9c-49be-88d3-21f5d3e9b08c.png)

**Desktop**
 - OS: Not applicable
 - Browser Not applicable
 - Version Not applicable

**Smartphone**
 - Device:  Not applicable
 - OS:  Not applicable
 - Browser  Not applicable
 - Version  Not applicable

**Comment by swalahamani** [comment]
Thanks to the [StackOverflow thread ](https://stackoverflow.com/a/56096223/6793156), the issue got resolved!

Actually, it was related to the configuration we were using with [PM2](https://pm2.keymetrics.io/)!

For single-page applications, we have to use the option `--spa` for automatically redirecting all queries to the `index.html`. 
Kindly refer to the [PM2 doc](https://pm2.keymetrics.io/docs/usage/expose/) if you're interested to read more detail!
