### ISSUE TITLE
Broken Markdown contents found in newsletter

### ISSUE THREAD

**Issue by PatrickPrakash** [MakerGram/makergram.com-support#2]
**Describe the bug**
**Monthly newsletter** from MakerGram Subject **Digest for 2022/11/1** looks broken. The email is received with markdown content.

**To Reproduce**
1. Search for the email with the Subject **Digest for 2022/11/1**
2. View the email to see the contents.

**Expected behavior**
Expected an HTML snippet of the monthly digest without broken images and animated gifs.

**Screenshots**
![image](https://user-images.githubusercontent.com/29561980/200345582-cb80c27e-4892-459f-a1b3-d7e2a554f012.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Browser: Microsoft Edge 107.0.1418.26 (Official build) (64-bit) 

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: Android 13
 - Browser: Chrome

**Additional context**
Attaching the full email content in **.eml** file for reference
[[MakerGram] Digest for 2022_11_1.zip](https://github.com/MakerGram/makergram.com-support/files/9953022/MakerGram.Digest.for.2022_11_1.zip)

**Comment by PatrickPrakash** [comment]
@swalahamani Please check this issue!

**Comment by swalahamani** [comment]
Hi @PatrickPrakash 

Thanks for raising this.

Could you please share the raw email content via email to `swalah[at]makergram[dot]com`?

Please refer to this [Google Support Doc](https://support.google.com/mail/answer/29436?hl=en) to learn how to get the raw email content.

**Comment by patrickcavli** [comment]
Raw email content is attached within the zip file, will send the same via email

**Comment by PatrickPrakash** [comment]
Hey @swalahamani. I have already attached the raw mail data within the issue description. Will sent the same via email.

**Comment by swalahamani** [comment]
@PatrickPrakash We couldn't reproduce this issue. It might be because the email might have failed to load remote image assets embedded with it.

Please re-open it if you get the issue again.
